### ISSUE TITLE
Update to latest version of @expo/config-plugins

### ISSUE THREAD

**Issue by stefan-schweiger** [BelkaLab/expo-appcenter#2]
`@expo/config-plugins` is still at 4.x but version 5.x was released 6 month ago and expo doctor is complaining for SDK47 

```
Expected package @expo/config-plugins@^5.0.2
Found invalid:
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)
```

From `npm why @expo/config-plugins`:
```
@expo/config-plugins@4.1.5
node_modules/expo-appcenter/node_modules/@expo/config-plugins
  @expo/config-plugins@"^4.1.5" from expo-appcenter@0.1.2
  node_modules/expo-appcenter
    expo-appcenter@"^0.1.2" from the root project
```

**Comment by FRizzonelli** [comment]
Hi @stefan-schweiger! Thanks for the input :) Do you think you can share with us a small PR for the fix with the update? We aren't currently active on the repo but I'll release a new version on npm with the fix if you can provide a PR 🚀

**Comment by FRizzonelli-belka** [comment]
Hi @stefan-schweiger, I've released a new version from a PR. We updated the config plugin version with that. I'm closing this issue!
