### ISSUE TITLE
iOS build error: cannot initialize return object of type 'BOOL'

### ISSUE THREAD

**Issue by chriszs** [BelkaLab/expo-appcenter#5]
Got this with App Center 5.0.0 and Expo 49 when I run `npx expo run:ios`:

> ❌  (iOS/[APPNAME]/AppDelegate.mm:19:10)
>
>  17 |   self.initialProps = @{};
>  18 | 
> 19 |   return [AppCenterReactNative register];
     |          ^ cannot initialize return object of type 'BOOL' with an rvalue of type 'void'
  20 |   [AppCenterReactNativeAnalytics registerWithInitiallyEnabled:true];
  21 |   [AppCenterReactNativeCrashes registerWithAutomaticProcessing];

Seems like this may be what #4 fixes.

**Comment by FRizzonelli-belka** [comment]
Hi @chriszs, I've merged #4 so let me know if you still have the issue. I'm closing this one :)
